#!/bin/sh -Ceu

mnt=$1
tmp=${TMPDIR}/$(realpath "$mnt")

if mountpoint -q "$mnt"; then
    echo 'anything mounted'
    df -h "$mnt"
    exit 1
fi
if [ ! -d "$tmp" ]; then
    mkdir -p "$tmp"
fi
# mount --bind "$tmp" "$mnt"
unionfs -o nonempty "$tmp"=RW "$mnt"
