#!/bin/sh -Ceu

GIT_DIR="$HOME"/.dotfiles.git
if [ -e "$GIT_DIR" ]; then
	echo 'already cloned'
	exit 1
fi

git clone --bare https://github.com/xia4913/dotfiles.git "$GIT_DIR"
dotfiles config status.showUntrackedFiles no
dotfiles checkout
dotfiles remote set-branches --add origin master
dotfiles branch --set-upstream-to=origin/master master
