#!/bin/sh -Ceu

git-error-unless-inside
while getopts s f; do
	case $f in
	s)
		short=true
		;;
	\?)
		;;
	esac
done
shift $(( OPTIND - 1 ))

origin="$(git remote -v | awk '($1 == "origin" && $3 == "(fetch)") { print $2; }')"
if [ -z "$origin" ]; then
	exit 127
fi
if [ "${short:-}" != true ]; then
	echo "$origin"
else
	echo "$origin" | awk '
		{
			sub("^(https://|git@)github\\.com[/:]", "github:", $0);
			sub("\\.git$", "", $0);
			print;
		}
	'
fi
