#!/bin/sh -Ceu

re_prefix='^alias\.'
re_names=
if [ $# -ge 1 ]; then
  re_names=$(grex --capture-groups --no-start-anchor "$@")
fi
tab="$(printf '%b' '\t')"
git config --get-regexp "$re_prefix$re_names" | \
  sed 's/'"$re_prefix"'//; s/ /\t/' | column -ts "$tab"
