#!/bin/sh -Ceu

case ${1:-} in
--clone)
  shift
  ghr clone "$@"
  exit $?
esac

if [ $# -gt 0 ]; then
  set -- --query "$1"
fi
ghr list -p | sed 's|\([^/]*/[^/]*\)$|\1 \1|' | \
  s --with-nth 2 "$@" | choose 0
