#!/bin/sh -e

# shellcheck disable=SC2046
set -- $(shell-style-option "$@")
sh_opt=$1
shift

environ() {
	set-environ-command -"$sh_opt" "$@"
}

editors='ex ed editor'
if [ "$TERM" = dumb ]; then
	if [ -n "$INSIDE_EMACS" ]; then
		pagers='cat'
	else
		pagers='more'
	fi
else
	pagers='less more pager'
	editors="vi $editors"
fi

# shellcheck disable=SC2086
pager=$(command-available-first $pagers)
environ PAGER "$pager"
if [ "$pager" = less ]; then
	less_paging=-inRXaj5
	environ LESS_PAGING "$less_paging"
	environ LESS "$less_paging -F"
	environ LESSHISTFILE -
	environ LESSCHARSET utf-8

	blink=$(tput blink)
	bold=$(tput bold)
	red=$(tput setaf 1)
	cyan=$(tput setaf 6)
	reset=$(tput sgr0)
	underline=$(tput smul)
	reset_underline=$(tput rmul)
	environ LESS_TERMCAP_mb "$blink"
	environ LESS_TERMCAP_md "$bold"
	environ LESS_TERMCAP_me "$reset"
	environ LESS_TERMCAP_so "$bold$red"
	environ LESS_TERMCAP_se "$reset"
	environ LESS_TERMCAP_us "$underline$cyan"
	environ LESS_TERMCAP_ue "$reset_underline$reset"
fi

decorators=bat
environ DECORATOR "$(command-available-first "$decorators")"

editor=$(command-available-first "$editors")
environ EDITOR "$editor"

lists='exa ls'
list=$(command-available-first "$lists")
environ LIST "$list"
