#!/bin/sh -Ceu

time_column=bsdtime,start_time
ps_args="-o ppid,pid,nlwp,tname,stat,$time_column,command"
if dumb ps --sort pid r; then
	ps_args="$ps_args --sort uid,ppid,$time_column"
fi

pgrep_args=$*
if [ -z "$pgrep_args" ]; then
	if [ -n "$SHELL" ]; then
		pgrep_args="$pgrep_args -x $(progname -r "$SHELL")"
	fi
	if [ -n "$USER" ]; then
		pgrep_args="$pgrep_args -U $USER"
	fi
else
	ps_args="-o user $ps_args"
fi
case $(progname -r "$0") in
pgf)
	pgrep_args="-x $pgrep_args"
esac

# shellcheck disable=SC2086
pgrep $pgrep_args | xargs -r ps $ps_args p
