#!/bin/sh -eu

# shellcheck disable=SC2046
set -- $(shell-style-option "$@")
sh_opt=$1
shift

name=$1
shift
value=$*
if [ -n "$value" ]; then
	case "$sh_opt" in
	s)
		echo "$name='$value'; export $name"
		;;
	z)
		echo "export $name='$value'"
		;;
	c)
		echo "setenv $name '$value'"
		;;
	esac
fi
