#!/bin/sh -Ceu

# pop last argument
n=$#
while [ $(( n -= 1 )) -gt 0 ]; do
  set -- "$@" "$1"
  shift
done
query=${1:-}
shift

escape() {
  sed 's/\(["]\)/\\\1/g'
}
strip() {
  sed 's/^\s*//' | sed -z 's/\n/ /g; s/ $//'
}
post_data() {
  printf '{"query":"%s"}' "$(echo "$@" | strip | escape)"
}

curl-json "$@" -d "$(post_data "$query")"
