#!/bin/sh -Ceu

# pop last argument
n=$#
while [ $(( n -= 1 )) -gt 0 ]; do
  set -- "$@" "$1"
  shift
done
query=${1:-}
shift

escape() {
  echo "$@" | sed 's/\(["]\)/\\\1/g'
}
post_data() {
  printf '{"query":"%s"}' "$(escape "$@")"
}

curl-json "$@" -d "$(post_data "$query")"
