#!/bin/sh -Ceu

if [ -n "${TMPDIR:-}" ]; then
	cd "$TMPDIR"
fi

profile=$(progname -r "$0" | sed 's/[^-]*-*//')
if [ -z "$profile" ]; then
	profile=nightly
fi

log_dir=$(log-dir firefox/"$profile")
log=$log_dir/$profile
opt=$HOME/opt/firefox

case $profile in
beta|developer|nightly)
	bin=$opt/channels/$profile/firefox
	;;
*)
	bin=$opt/sandbox/nightly-no-update/bin/firefox
esac

pre=$opt/pre/$profile
if [ -x "$pre" ]; then
	"$pre"
fi

set -x
GDK_DPI_SCALE=0.5 MOZ_ENABLE_WAYLAND=1 MOZ_LOG_FILE="$log" \
  ja "$bin" -P "$profile" "$@"
