#!/bin/sh -Ceu

case ${XDG_CURRENT_DESKTOP:-} in
niri)
 ;;
*)
 cd ~/tmp
 unset SHLVL

 PATH=~/bin/wayland/niri:~/bin/wayland:$PATH
 systemctl --user import-environment \
  SHELL PATH PAGER EDITOR TMPDIR SSH_AUTH_SOCK

 niri validate
esac
niri --session "$@"
