#!/bin/sh -Ceu

opt_files=false
for i in $(basename "$0" | fold -1); do
	case $i in
	f)
		set -- -F "$@"
		;;
	l)
		set -- -l "$@"
		opt_files=true
		;;
	s)
		set -- -s "$@"
		;;
	w)
		set -- -w "$@"
	esac
done

grep=rg-
if [ "$opt_files" = true ]; then
	"$grep" --color=never "$@"
else
	"$grep" "$@" | p
fi
