#!/bin/sh -Ceu

for i in $(basename "$0" | fold -1); do
	case $i in
	1)
		set -- -m1 "$@"
		;;
	f)
		set -- -F "$@"
		;;
	l)
		set -- -l --color=never "$@"
		;;
	s)
		set -- -s "$@"
		;;
	w)
		set -- -w "$@"
	esac
done
rg- "$@" | p
