#!/bin/sh -Ceu

if [ $# -eq 1 ] && [ -d "$1" ]; then
	faketty l "$@" | "$PAGER"
	exit
fi
if ! isatty stdout; then
	cat "$@"
	exit
fi
if ! isatty stdin; then
	"$PAGER" "$@"
	exit
fi

if [ -n "${PAGING:-}" ]; then
	set -- --paging="$PAGING" "$@"
fi
bat "$@"
