#!/bin/sh -Ceu

name=${1:-}

if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
	dir=$XDG_RUNTIME_DIR/log
elif [ -n "${TMPDIR:-}" ]; then
	dir=$TMPDIR/log
else
	dir=$HOME/log
fi
if [ -n "$name" ]; then
	dir="$dir/$name"
fi

umask 077
mkdir -p "$dir"
echo "$dir"
