#!/bin/sh -Ceu

opt_raw=false
while getopts r f; do
    case $f in
    r)
        opt_raw=true
        ;;
    *)
    esac
done
shift $(( OPTIND - 1 ))

path=$1
progname=$(basename "$0")
case $progname in
sub-dir)
    _path=$(command -v "$path" || :)
    if [ -n "$_path" ]; then
        path=$_path
    fi
    echo "$(dirname "$path")/$(basename "$path").d"
    ;;
*)
    if [ "$opt_raw" != true ]; then
        path=$(realpath "$path")
    fi
    case $progname in
    progdir)
        dirname "$path"
        ;;
    progname)
        basename "$path"
        ;;
    esac
esac
