#!/bin/sh -Ceu

name=${1:-}

tmp_dir="${TMPDIR:-$(tmp-dir)}"
run_dir="$tmp_dir"/run
if [ -n "${XDG_RUNTIME_DIR:-}" ]; then
	if [ ! -d "$run_dir" ]; then
		ln -s "$XDG_RUNTIME_DIR" "$run_dir"
	fi
	run_dir="$XDG_RUNTIME_DIR"
else
	(umask 077; mkdir -p "$run_dir")
fi

dir=$run_dir
if [ -n "$name" ]; then
	dir=$dir/$name
	(umask 077; mkdir -p "$dir")
fi
echo "$dir"
