#!/bin/sh -Ceu

mode=
while getopts elvw f; do
	case $f in
	e)
		mode=show
		;;
	l)
		mode=list
		;;
	v)
		mode=verbose
		;;
	w)
		mode=which
		;;
	\*)
		echo "unknown option: $1"
		exit 1
		;;
	esac
done
shift $(( OPTIND - 1 ))

main="$1"; shift

dir="$(sub-dir "$main")"

if [ "$mode" = list ]; then
	prefix="$main-"
	(cd "$dir"; ls -1d "$prefix"*) | sed "s|^$prefix||" | sort
	exit
fi

sub="$1"; shift
name="$main-$sub"

if is-command-available "$name"; then
	path="$name"
elif [ -x "$dir/$name" ]; then
	path="$dir/$name"
else
	echo "$main: '$sub' is not found."
	exit 1
fi

case $mode in
which)
	echo "$path"
	exit
	;;
verbose)
	set -x
esac
"$path" "$@"
