#!/bin/sh -Ceu

prompt="${1:-?}"
y="${2:-y}"
n="${3:-n}"
s=$(printf '%s (%s/%s) ' "$prompt" "$y" "$n")
while :; do
	printf %s "$s"
	answer=$(getch)
	echo "$answer"
	case $answer in
	"$y")
		exit 0
		;;
	"$n")
		exit 1
		;;
	esac
done
