#!/bin/sh -Ceu

prompt="${1:-?}"
yes="${2:-yes}"
no="${3:-no}"
s=$(printf '%s [%s/%s] ' "$prompt" "$yes" "$no")
while :; do
	printf %s "$s"
	read -r answer
	case $answer in
	"$yes")
		exit 0
		;;
	"$no")
		exit 1
		;;
	esac
done
